
// ===================================================== \\
// ===================================================== \\
//                      Utilities
// ===================================================== \\
// ===================================================== \\


/* ===================================================== *\
|| Store data to local                                   ||
\* ===================================================== */
    function storeData(key, data) {
        chrome.storage.local.set({ [key]: data }).then(() => {
            console.log("Value is set");
        });
    }

/* ===================================================== *\
|| Retrieve data from to local                           ||
\* ===================================================== */
function retrieveData(key) {
    return chrome.storage.local.get([key]).then((result) => {
        console.log("Value is " + result.key);
    });
}

/* ===================================================== *\
|| Format and display the collected data for each site   ||
\* ===================================================== */
function formatDisplaySiteStats() {
    let urlData = retrieveData("urlData");
    let display = "DATA:";

    urlData.foreach((item) => {
        display += "\n" + item;
    })

    return display;
}

/* ===================================================== *\
|| Display data to html page                             ||
\* ===================================================== */
function dispayToPage(currentUrl) {
    document.getElementById('currUrl').textContent = "Curr Page " + currentUrl;

    formatDisplaySiteStats().then(display => {
        document.getElementById('urlData').textContent = display;
    });
}

// ===================================================== \\
// ===================================================== \\
//                      Main Script
// ===================================================== \\
// ===================================================== \\


let urlData = [];

// Get current active tab URL
//      Generated by: Google Gemini (Bard)
chrome.tabs.query({ active: true, currentWindow: true }, function(tabs) {
    let currentUrl = null;

    // check if tabs exist
    if (tabs && tabs.length > 0) {
        const currentTab = tabs[0];
        currentUrl = currentTab.url;

    } else {
        document.getElementById('currUrl').textContent = "Could not find active tab";
    }

    // if we have current url add to local store
    if (currentUrl) {
        // store new url
        retrieveData("urlData").then(storedData => {
            if(storedData){
                urlData = storedData;
            }

            // update stored data
            urlData.push(currentUrl);
            storeData("urlData", urlData);
        })

        dispayToPage(currentUrl);

    } else {
        dispayToPage("Could not get URL");
    }
});


// NOTE: for website time spent maybe have logic that only sites that are visited more then once
//      or for longer then a user selected time are stored. That way your useage is not clutted
//      by quick hops
